# Generated by Django 5.2.17 on 2026-09-21 23:37

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='reçue le')),
                ('name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('company', models.CharField(blank=True, max_length=150, verbose_name='société')),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='fonction')),
                ('phone', models.CharField(max_length=40, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('wilaya', models.CharField(blank=True, choices=[('01', '01 — Adrar'), ('02', '02 — Chlef'), ('03', '03 — Laghouat'), ('04', '04 — Oum El Bouaghi'), ('05', '05 — Batna'), ('06', '06 — Béjaïa'), ('07', '07 — Biskra'), ('08', '08 — Béchar'), ('09', '09 — Blida'), ('10', '10 — Bouira'), ('11', '11 — Tamanrasset'), ('12', '12 — Tébessa'), ('13', '13 — Tlemcen'), ('14', '14 — Tiaret'), ('15', '15 — Tizi Ouzou'), ('16', '16 — Alger'), ('17', '17 — Djelfa'), ('18', '18 — Jijel'), ('19', '19 — Sétif'), ('20', '20 — Saïda'), ('21', '21 — Skikda'), ('22', '22 — Sidi Bel Abbès'), ('23', '23 — Annaba'), ('24', '24 — Guelma'), ('25', '25 — Constantine'), ('26', '26 — Médéa'), ('27', '27 — Mostaganem'), ('28', '28 — M’Sila'), ('29', '29 — Mascara'), ('30', '30 — Ouargla'), ('31', '31 — Oran'), ('32', '32 — El Bayadh'), ('33', '33 — Illizi'), ('34', '34 — Bordj Bou Arréridj'), ('35', '35 — Boumerdès'), ('36', '36 — El Tarf'), ('37', '37 — Tindouf'), ('38', '38 — Tissemsilt'), ('39', '39 — El Oued'), ('40', '40 — Khenchela'), ('41', '41 — Souk Ahras'), ('42', '42 — Tipaza'), ('43', '43 — Mila'), ('44', '44 — Aïn Defla'), ('45', '45 — Naâma'), ('46', '46 — Aïn Témouchent'), ('47', '47 — Ghardaïa'), ('48', '48 — Relizane'), ('49', '49 — Timimoun'), ('50', '50 — Bordj Badji Mokhtar'), ('51', '51 — Ouled Djellal'), ('52', '52 — Béni Abbès'), ('53', '53 — In Salah'), ('54', '54 — In Guezzam'), ('55', '55 — Touggourt'), ('56', '56 — Djanet'), ('57', '57 — El M’Ghair'), ('58', '58 — El Meniaa'), ('abroad', 'Hors Algérie')], max_length=10, verbose_name='wilaya')),
                ('need', models.CharField(choices=[('infrastructure', 'Infrastructure & courant faible'), ('software', 'Logiciel / ERP'), ('equipment', 'Équipements IT'), ('iso', 'ISO & Consulting'), ('anpdp', 'Conformité ANPDP'), ('hvac', 'HVAC-CVC'), ('other', 'Autre')], max_length=20, verbose_name='type de besoin')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('attachment', models.FileField(blank=True, storage=contact.models.private_storage, upload_to=contact.models.attachment_path, verbose_name='pièce jointe')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='nom du fichier')),
                ('consent', models.BooleanField(default=False, verbose_name='consentement')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement donné le')),
                ('lang', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2, verbose_name='langue')),
                ('page', models.CharField(blank=True, max_length=500, verbose_name='page d’origine')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('in_progress', 'En cours'), ('done', 'Traitée'), ('spam', 'Indésirable')], db_index=True, default='new', max_length=20, verbose_name='statut')),
                ('notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='notification envoyée le')),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmation envoyée le')),
            ],
            options={
                'verbose_name': 'demande de contact',
                'verbose_name_plural': 'demandes de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
