# Generated by Django 5.2.17 on 2026-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='need',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure & courant faible'), ('software', 'Logiciel / ERP'), ('equipment', 'Équipements IT'), ('iso', 'ISO & Consulting'), ('anpdp', 'Conformité Loi 18-07'), ('hvac', 'HVAC-CVC'), ('other', 'Autre')], max_length=20, verbose_name='type de besoin'),
        ),
    ]
